### ISSUE TITLE
File not working on Flutter Web

### ISSUE THREAD

**Issue by mayankjanmejay** [tekartik/fs_shim.dart#16]
Hello I tried using your plug in Flutter for Web and it just does not work. Below is the code. Could you please help?

somethingElse()
async {
 
 FileSystem fs = ioFileSystem;
  // safe place when running from package root
  String dirPath = (Directory.current.path);

  // Create a top level directory
  // fs.newDirectory('/dir');
  Directory dir = new Directory(dirPath);

  // delete its content
  await dir.delete(recursive: true);

  // and a file in it
  // fs.newFile(join(dir.path, "file"));
  File file = new File(dir.path+ "file.txt");

  // create a file
  await file.create(recursive: true);
  await file.writeAsString("Hello world!");

  // list dir content
  print(await dir.list(recursive: true, followLinks: true).toList());
}

**Comment by alextekartik** [comment]
Sorry for the lack of documentation but indeed it can support flutter web. ioFileSystem is for io (flutter, vm) only. While on flutter io (iOS, Android) you have:

```
FileSystem fs = ioFileSystem;
```

on Web you need to use a different file system (on top of indexed_db)

```dart
FileSystem fs =
    newFileSystemIdb(idbFactoryNative) as IdbFileSystem;
```

See the example here: https://github.com/tekartik/fs_shim.dart/blob/master/fs/example/browser/main.dart

**Comment by mayankjanmejay** [comment]
Hey, Thanks a lot for your reply. 
I tried using the example as follows but it doesn't create a file. 

FileSystem fs =
    newFileSystemIdb(idbFactoryNative) as IdbFileSystem;
generateFile()
{
final dir = fs.directory('C:/');
  print(dir);
  final file = fs.file(dir.path+ "file.txt");
  print(file);
  print(dir.path);
  await file.create(recursive: true);
  await file.writeAsString("Hello world!");
  if (fs.supportsFileLink) {
    final link = fs.link(dir.path+ 'link');
    print(dir.path);
    print(link);
    await link.create(file.path);    
  }
  print(await dir.list(recursive: true, followLinks: true).toList());
}

______________________________
Output 

Directory: 'C:/'
File: 'C:/file.txt'
C:/
C:/
Link: 'C:/link' but still no file. What am I doing wrong?

**Comment by alextekartik** [comment]
For security reason there is no way to create a file on your Desktop file system. Here the file is stored in an indexed_db database in your browser that you can manipulate using a similar API, however it is not an IOFile that can extract and view on your Desktop.

**Comment by mayankjanmejay** [comment]
So there is no way of generating an actual downloadable file?

**Comment by alextekartik** [comment]
Yes you can using dataURI: https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server

fs_shim will just help you having the content persistent in the browser. Then you generate a data URI from its content.
