### ISSUE TITLE
Does fs_shim support random read/writes

### ISSUE THREAD

**Issue by bsutton** [tekartik/fs_shim.dart#38]
I need a solution that works for large files (GB+) within a browser.

The storage system must not require any user interactions to create/read/write files.

The storage system needs to provide seek style operations with efficient read/write operations to parts of a large file.

Does fs_shim allow this?

I can't find any references to the likes of RandomAccessFile.
I'm assuming that give fs_shim is backed by indexed_db that it requires no user permissions but I'm unable to find any definitive statement on this.

**Comment by alextekartik** [comment]
Random access file is not supported. The fs_shim File API is a subset of the File io API with openFile/stream/sink removed, basically what you need. However this could be considered, assuming we can have a reasonable web implementation. What would be the API you need from the File io API ?

**Comment by bsutton** [comment]
I've done some experimental work using Isar with a file/page entity (Isar
sits on top of indexed db for web).
The file data is stored as a set of pages each upto 16KB.

If I've understood your code correctly, this is similar to your file/node
structure.

I've written a class modelled on RandomAccessFile that provides
read/write/seek access.

So one thought is to merge this implementation with your code.

My objective is to have identical code across platforms.

The web implementation needs to allow access to GB+ files which can be
updated without causing the browser to run out of memory.
In my implementation I cache the 'page' objects up to a defined limit (100
pages by default).
This provides fast in memory access to small files whilst allowing me to
stream large files and write to any location with reasonable performance.

Does this sound like it would match what you are doing?
Would you be interested in collaborating to have something like my
RandomAccessFile class merged?

**Comment by alextekartik** [comment]
> Does this sound like it would match what you are doing?

It could definitely fit here (in this fs_shim project). The idea behind fs_shim was that a sample code using dart:io could easily be ported on the web. I opinionatedly filtered out any synchronous API as indexeddb only supports async operation. So we could have a RandomAccessFile modeled this way (i.e. with readByte but not readByteSync). 

I won't have much time to work on that by the end of the year. It is important that I put in place some performance comparison (I have some internal ones). I could definitely adapt the implementation of the storage itself (we could keep the file system tree handling as is) to support multiple/custom implementation. Currently streaming is really bad but ok if done in one shot (writeAsBytes, writeAsString).

Some issues and thoughts
- compatibility: currently one file is one record, nothing can beat that for File.writeBytes which matches 99% of the usage for small files. Whatever solution should be compatible with the existing if no code is changed.
- model a solution that works for all. Streaming a 10GB file to 16KB records might not be super efficient. i.e. maybe 16KB pages works for you but not for other usage, so maybe this (page size) could be a settings in the FileSystem (which is the abstraction level in fs_shim), thinking here again about compatibility if the settings change (or not being compatible at all, imposing that a file system has a fixed initial page size that can never change)
- being cross tab safe, at least not worst than 2 io app writing on the same. All operation in an indexed db transaction should provide a good level cross tab locking solution
- ability to work in a web/shared worker.

You could also take a look at sqlite3 web file system implementation here: https://github.com/simolus3/sqlite3.dart/blob/main/sqlite3/lib/src/wasm/file_system.dart.

> Would you be interested in collaborating to have something like my
> RandomAccessFile class merged?

So yes ! Thanks 

Maybe let's first select the API you really need (i.e. maybe not provide lock/unlock as I'm not sure what would be the cross tab solution that would not hang forever if a tab is killed while locking, a database transaction on indexed db cannot be held open for a given duration, it terminates as soon as possible)

**Comment by bsutton** [comment]
My implementation also ignores the sync methods as I don't see any effective method of implementing them and unlike dart:io they wouldn't provide any improved performance.


> currently one file is one record
My (untested thoughts) was that the file/page db structure wouldn't add much overhead because in most cases small files will fit into one page.
I suppose if you wanted to eliminate the 2nd read we could store the first page in the file entity and then subsequent pages in a page entity.

I gather that you would want to support the filesystem structure for existing users in a backward compatible way hence your statement `support multiple/custom implementation.`
Any changes here are going to break you existing 'storage format' contract with existing users.
Do you have any meta data stored in the files or filesystem?
I'm thinking that we could add a 'filesystem' meta data entity to detect the version of the implementation.
With your existing users the lack of the filesystem meta data tells that they are using your current v1 implementation.
This would facilitate automatic upgrades of a user's filesystem going forward.

> so maybe this (page size) could be a settings
Yes this make sense - as noted above this could be stored in the filesystem meta data.
For performance reasons we will need to ensure that every page in a filesystem is the same size (otherwise we can't calculate the page to read for a given offset).


One advantage of my experimental implementation is that it uses Isar as the storage mechanism.
This means that I can test on a desktop platform which has much faster turn around times that having to test in a browser. Isar handles all of the platform abstraction. The downside is that it will be less performant in a dart:io environment as it still uses a db when a native file system is available.  One Idea I was playing with was to get my v1 implementation out using isar and then go back and build an alternate variant that talks directly to the file system for dart:io platforms. So essentially an abstraction layer above Isar.

Would you be open to using Isar as the db?

When running in a dart:io environment how is your code reading/writing to files. Is it directly using the file system?

The sql3lite implementation looks a little too experimental as I need a production ready implementation.

Locking - my requirements don't particularly need locking. I can probably just warn users if they open a second tab.

If we do locking it would probably have to be for the entire file. Range based locking would probably be very expensive.

The following scheme might work.

When taking a lock a tab (the 'owning tab') generates a 'per tab' unique id.
The unique id is stored in the 'file' entity to indicate that a lock has been taken.
The tab then opens a broadcast channel to respond to 'heart beat' requests from other tabs.

When another tab (the 'waiting tab') attempts to lock the file and the file is already locked it uses the above BroadcastChannel to send a heart beat with the 'per tab unique id' of the tab that owns the lock.
If the tab fails to respond to the broadcast then we assume that the tab is dead and forceably take the lock.
If the owning tab is alive then the 'waiting tab' sleeps for 'n' millseconds and retries the above process.
We could have the 'owning' tab send a broadcast message when it releases the lock if we could implement some process that can wake the sleeping 'waiting tab'. This could reduce the latency of waiting for 'n' milliseconds for the lock to be released.

I'm not certain of the performance characteristics of the broadcast channel.
Service worker post messages is might be an alternate. I'm not familiar with the details/limitations of these.

If broadcast messages were faster then reading the file entity from the db then we could keep file locks in memory using a broadcast mechanism to take/release locks.
The heartbeat process would still be required and each tab would have to keep its own list of all file locks held by all tabs.
If an owning tab fails to respond to a heart beat then  all 'other' tabs can flush any locks held by that tab from their in memory lock table.

Each of these mechanisms suffer from a race conditions when two (or more) tabs both try to lock the same file.
We could use an optimistic locking mechanism - read the file entity and check if it's locked. If not, add our lock guid and write the file. Re-read the file to see if our guid is in the lock entry. If it isn't, that means some other tab got the lock first and we fall back to the above waiting methods.



Any other ideas?

**Comment by alextekartik** [comment]
> One advantage of my experimental implementation is that it uses Isar as the storage mechanism.
> This means that I can test on a desktop platform which has much faster turn around times that having to test in a browser

fs_shim uses itself an abstracted indexeddb (idb_shim) which also works on io/memory which allow testing everything in a regular dart vm test which is good since the indexeddb API is not very "dart".

> Would you be open to using Isar as the db?

Not in fs_shim directly but there could be a fs_shim_isar implementation. Basically the only thing to implement is a `FileSystem` object.

fs_shim already supports custom implementation, it works in memory, web, io but I also have a private google storage implementation (not all api supported but I can list and write files) and a remote file access (that I cannot unfortunately share)

> When running in a dart:io environment how is your code reading/writing to files. Is it directly using the file system?

When running in dart:io the native File api is called, when running on the web, indexeddb is used.

> Locking - my requirements don't particularly need locking. 

As I said, indexeddb transaction already provide store (i.e. our records) locking between tabs so we are safe in a transaction. positing message will likely not be realtime ready for concurrent access.

I have sanitized the API RandomAccessFile I plan to support here (and it already works on io but not on the web yet):
https://github.com/tekartik/fs_shim.dart/blob/master/fs/lib/src/random_access_file.dart

(basically without the sync function and without lock/unlock).

Sorry if it does not go the Isar route you have in mind, as I said fs_shim allow for custom FileSystem implementation so there is definitely a solution to have your own FileSystemIsar working on both io and web.

**Comment by alextekartik** [comment]
Random access support has been added. Default web implementation (`fileSystemWeb`) is not optimized for it but you can tune it for you needs (and it might become the default in the future). 16Kb page gives ok result in common scenarios:

```dart
import 'package:fs_shim/fs_browser.dart';

// 16Kb page default
final fs =
    fileSystemWeb.withIdbOptions(options: FileSystemIdbOptions.pageDefault);
```

Storage remains compatible whatever options is used.

**Comment by bsutton** [comment]
Nice!
