### ISSUE TITLE
Support Platform class in fs_shim/fs_io.dart

### ISSUE THREAD

**Issue by ekuleshov-idexx** [tekartik/fs_shim.dart#47]
When replacing

`import 'dart:io';`

with

`import 'package:fs_shim/fs_io.dart';`

It would be really handy to have `Platform` class (from `dart:io`) also supported when running on web.

So, calls like `Platform.isAndroid`, `Platform.isIOS`, etc. would return correct platform the web browser running in.

**Comment by alextekartik** [comment]
Interesting, although I'm not sure this should be part of this package. I think there are some packages that performs that: https://pub.dev/packages/platform_detect or https://pub.dev/packages/universal_io but I have not tried that myself yet (I typically perform my own user agent parsing to detect the platform)

**Comment by ekuleshov-idexx** [comment]
@alextekartik thank you for giving it a thought.

I actually want to replace `universal_io` with `fs_shim`. The former is very limited and does not provide full `fs` emulation on web, e.g. no `Directory` support at all and `File` API is backed by the local storage - so sizes you can store are very limited.

I can get around with not having "universal" or "shim" `Platform`, but it is just extra code to support web.

It also seems like this package is one step away from "drop-in" io replacement on web as all the pieces needed for it already there.

**Comment by alextekartik** [comment]
You might be able to merge with other solution with something like:

```dart
import 'package:fs_shim/fs_shim.dart';
import 'package:universal_io/io.dart'
    hide
        Directory,
        File,
        Link,
        FileSystemEntity,
        FileMode,
        FileStat,
        OSError,
        FileSystemException,
        FileSystemEntityType;
```

**Comment by ekuleshov** [comment]
@alextekartik yes, I know, but I was hoping the `io` "shim" could do that without dragging in another plugin only for the `Platform` class. Currently I'm basically prefixing all "io" `Platform` calls with `!kIsWeb`.
