### ISSUE TITLE
Support fs_io on web

### ISSUE THREAD

**Issue by ekuleshov-idexx** [tekartik/fs_shim.dart#48]
Currently the `fs_io` doesn't seem to work on web and you have to fall back to `fs_shim.dart` and direct use of `fileSystemWeb.file()` in order to use `File` API on the web.

It would be really neat if the `fs_io` worked out of the box on the web too.

**Comment by alextekartik** [comment]
Ok I understand. I think we could have a concept of *default file system*. fs_io would not even be needed then. I'll look into it.

**Comment by ekuleshov-idexx** [comment]
Awesome! Thank you.

**Comment by alextekartik** [comment]
You might want try the version is just published: 2.2.0-1

tmp dependency until published to stable:
```
  fs_shim: '>=2.2.0-1'
```

You should be able to the the File API (and constructors) on the web too. There is a global `fileSystemDefault` which is initialized for the target platforms.

**Comment by ekuleshov** [comment]
Great stuff! I tried it out and with the new change the `fs_io` and all explicit `fs` factories aren't needed anymore.

...if only `dart:io` Platform were working on web #47, we'd have complete drop-in replacement for `io` API on the web. :)

Thank you again for your work on this.
